### ISSUE TITLE
Problem with download dataset

### ISSUE THREAD

**Issue by jdiazram** [PalaashAgrawal/STUPD#1]
Hi, excellent job.
I try to download the entire dataset, but in parts, with the link of each, against_part01.zip, against_part01.zip, etc. So, try to unzip each file, and I got this message:

![Screenshot from 2024-05-06 14-36-21](https://github.com/PalaashAgrawal/STUPD/assets/45439493/1b01a138-51ad-44a7-99b2-fa5bce616b00)

Is there a way to download by part, like groups "against," "along," etc.?

Thx

**Comment by PalaashAgrawal** [comment]
Hi @jdiazram, 
Thanks for bringing this to my attention, and sorry for the inconvenience
Can you please give me till Friday to fix this issue? Seems like there was an issue while zipping the files. 
I'll reupload the dataset

**Comment by jdiazram** [comment]
Hi @PalaashAgrawal 
Were you able to re-upload the dataset? 
Thank you.

**Comment by PalaashAgrawal** [comment]
Hi Jorge,
I have decided to reupload the dataset as a multipart zip file, but zipping
is taking a long time, because i have limited CPU cores.

About your other question, the problem is that google wont let you upload a
zip file >3GB, so i have to split the folders by size. But I think there
isn't any restriction on downloading, so if i put all the parts of a
particular group in a separate folder, you can download them all at once,
and then recursively unzip on your terminal.

Is there a specific label that you're interested in exploring, or the
entire dataset in general? Uploading the entire dataset will take a little
time, but I can try to prioritize the ones you want to use earlier.
Also you can still download all the files that named <label>.zip (vs
<label-part1.zip>). They are the static categories, which have no inherent
motion in each example.

THanks for your patience
Palaash
ᐧ

**Comment by PalaashAgrawal** [comment]
Hi @jdiazram, 
I have resolved the issue. You can go ahead and explore the dataset. 
The folders are separated, so you can also download individual categories separately,
